apiVersion: rbac.authorization.k8s.io/v1
#k create rolebinding config-view --clusterrole view
#  --user system:serviceaccount:default:default --namespace default
kind: RoleBinding
metadata:
  name: config-view
  namespace: default
subjects:
  - kind: User
    name: system:serviceaccount:default:default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: view # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io